name: remote ssh command

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Execute SSH commmands on remote server
        uses: appleboy/ssh-action@master
        with:
          host: zeein.co.kr
          # username : violet
          # username: ${{ secrets.USERNAME }}
          username: zeein
          # password : zeein39464000
          password: zeein39464000
          # password: ${{ secrets.PASSWORD }}
          port: 22
          # port: ${{ secrets.PORT }}
          script: |
            whoami
            la -al
          # cd /Users/violet/htdocs/zeeincokrinclude/wp-content/themes
          # rm -rf zeein-includesys
          # git clone https://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@github.com/zzin/zeein-includesys.git zeein-includesys
